### ISSUE TITLE
Nowy module: autoryzowanie użytkownika z różnych serwisów

### ISSUE THREAD

**Issue by debian-sh** [Sealious/sealious#104]
Przydałby się nowy moduł, który dałby możliwość logowania/rejestracji użytkownika do aplikacji za pomocą istniejącego konta Google, Facebook, Twitter i OpenID. Jedno z pytań jakie mi się nasuwa to co z user_id, które generuje automatyczne framework. Drugie czy dobrze nie byłoby tworzyć oddzielnych modułów na każdy typ konta (oddzielny dla Google, etc.). Zacząłem przeglądać API wszystkich serwisów i wszędzie to są kobyły z którymi developer musi się zmagać.

**Comment by simplypixi** [comment]
Temat był już kiedyś poruszany.
Proponowane przeze mnie rozwiązanie: https://github.com/hapijs/bell
Co jest nie tak z user_id?


Mariusz Wójcik
tel. 507-386-287

Napisz wiadomość >> <pixiproject@gmail.com>
Przejdź do portfolio >> <http://simplypixi.portfoliobox.me/projects>
[image: 2]
<http://oferia.pl/wykonawca/pixel93/323171?utm_source=powiad&utm_medium=email&utm_campaign=sygnatura_mail>

W dniu 16 marca 2015 00:29 użytkownik Arkadiusz Wieczorek <
notifications@github.com> napisał:

**Comment by groovy354** [comment]
Jest to szeroki temat do przegadania na spotkaniu. 

Problematyczne kwestie to, m.in:
* czy założenie konta za pomocą np. Facebooka sprawia, że do danego konta można się dostać tylko za pomocą Facebooka? 
* trzeba znaleźć warstwę abstrakcji na kanał autoryzacji. Dzięki temu łatwo będzie dodać moduły do np. OAuth. Jeżeli uczynimy kanały autoryzacji modulowymi, implementacja nowego sposobu logowania będzie drastycznie uproszczona

**Comment by debian-sh** [comment]
Pomysł dla przykładu logowania przez konto fb:

1. Klikam na ikonkę logowania przez facebook'a
2. User wprowadza swoje dane do logowania fb
3. Sealious zczytuje dane z serwisu facebook, próbuje doszukać się adresu mail.
4. User może poprawić te dane, jeśli wszystko jest ok, potwierdza przez SIGN IN
5. Na podanego maila przychodzić link aktywacyjny
 - ważne bez potwierdzenia konto jest aktywne przez 7 dni, po upłynięciu tego czasu konto wygaśnie
6. Jeśli user aktywuje konto przez link aktywacyjny, konto jako username ma mail podany przy punktach 3-4.

W przypadku wygaśnięcia facebook'owego konta user nie ma możliwości zalogowania się.

![Tablica](https://dl.pushbulletusercontent.com/TtL0Jluw7QkdWncXpw9wTREcc4j3Ryua/IMG_20150316_122002.jpg)

**Comment by groovy354** [comment]
Any discussion on this feature should continue on our [trello board](https://trello.com/c/KJKyC6gJ/2-abstract-chip-type-for-user-authentication-methods-fb-google)
