### ISSUE TITLE
Kompatybilność z NPM

### ISSUE THREAD

**Issue by groovy354** [Sealious/Sealious#106]
Aktualnie Sealious nie działa po instalacji z npm, ponieważ nie są spełniane wszystie `dependencies` modułu `base-chips`. 
Należy uczynić moduły sealiousowe pełnoprawnymi pakietami npm, aby mogły być łatwo require'owane i instalowane.

**Comment by debian-sh** [comment]
Przetestowane na VPSie, instalacja przebiegła bez zarzutu.

**Comment by groovy354** [comment]
Super :)
