### ISSUE TITLE
Pomysły do strony wizytówki

### ISSUE THREAD

**Issue by debian-sh** [Sealious/Sealious#107]
Aby bardziej zainteresować deweloperów myślę, że warto by zrobić np. live viewu dla RESTowego API.
Zakładam, że w locie dany odwiedzający może przetestować działanie RESTa coś na zasadzie codepen,  wpisuje własną jsonową konfigurację, uruchamia moduł rest i może sobie wysyłać GETy i POSTy.
Co sądzicie? Może macie inne pomysły?

**Comment by simplypixi** [comment]
Lepiej chyba podpiąć Swagger'a, ale niech reszta się wypowie. ;)

Mariusz Wójcik
tel. 507-386-287

Napisz wiadomość >> <pixiproject@gmail.com>
Przejdź do portfolio >> <http://simplypixi.portfoliobox.me/projects>
[image: 2]
<http://oferia.pl/wykonawca/pixel93/323171?utm_source=powiad&utm_medium=email&utm_campaign=sygnatura_mail>

W dniu 17 marca 2015 17:42 użytkownik Arkadiusz Wieczorek <
notifications@github.com> napisał:

**Comment by groovy354** [comment]
@debian-sh Codepen jest do frontendu. Co Twoim zdaniem musiałoby być zawarte w takim codepenowym snippecie?
@simplypixi Uczynienie Sealiousa kompatybilnym ze Swaggerem brzmi jak dobry pomysł. Ale nie mogę zczaić, co tak naprawdę robi lub czym ten Swagger jest :D Czy chciałbyś zająć się researchem w tej kwestii?

**Comment by simplypixi** [comment]
Swagger'a podpinałem do node'a w ramach REST Api Allegro, więc myśle, że
research nie będzie potrzebny. ;)

**Comment by groovy354** [comment]
Ok, to powiedz nam wszystkim, co robi lub czym jest Swagger? Bo nie czaję z
ich strony :)

**Comment by simplypixi** [comment]
Generalnie umożliwia nam wykonywanie zapytań restowych z wygenerowanej
przez siebie podstrony.
Wystarczy "oznaczyć" zapytania, określić w jaki sposób mają być walidowane,
a Swagger załatwi resztę.

**Comment by groovy354** [comment]
Czyli Swagger siedzi we front-endzie, tak?

**Comment by debian-sh** [comment]
Narodził mi się pomysł zakładki, podstrony "About us", jakieś super foto wspólne i parę słów albo indywidualnie o członkach albo ogólnie o całej grupie.

**Comment by groovy354** [comment]
Hmm imo dobry pomysł. Co inni na to?

**Comment by debian-sh** [comment]
Muszę zapisać bo zapomnę OpenSans na główny font dla contentu

**Comment by debian-sh** [comment]
Kolejny pomysł diagram jakieś flow, które pokaże w prosty i przystępny sposób wszystkie nasze koncepty, wykorzystanie sealious-base-chips, jak to wszystko współgra. Moim zdaniem 2-3 diagramy są w stanie czasem więcej powiedzieć 5-6 stron dokumentacji. Co nie oznacza, że nie potrzebujemy dokumentacji, ale to idzie innym torem.

**Comment by debian-sh** [comment]
Dodać marginesy do jednego z RWD w trybie pionowym.

**Comment by groovy354** [comment]
Strona wizytówkowa jest już bardzo ładna - pozostaje nam być może pomyśleć nad logo, ale to kwestia na osobny issue. Zamykam :)
