### ISSUE TITLE
REST - Brak zabezpieczeń w API

### ISSUE THREAD

**Issue by debian-sh** [Sealious/Sealious#110]
Dany użytkownik POSTując dane dla konkretnego zasobu ustawia owner_id, inny użytkownik choć posiada inne user_id ma prawo do zrobienia DELETE i PUT na tych danych.

Druga kwestia pomyślna autoryzacja usera daje mu dostęp tylko do wykonywania metody POST.

**Comment by groovy354** [comment]
Sprawa jest rozwiązywana na branchach z kontekstami i strategiami dostępu (będzie w ^0.4.0) :)
