### ISSUE TITLE
Session manager - przekierowanie po logowaniu

### ISSUE THREAD

**Issue by groovy354** [Sealious/Sealious#112]
Do metody `/login` przyjmować dodatkowy atrybut POST z urlem, na który mamy przekierować klienta po zalogowaniu pomyślnym i dokonać stosowne przekierowanie 301

**Comment by groovy354** [comment]
Rozwiązane w repo base-chips https://github.com/Sealious/sealious-base-chips/commit/b6c279926cc80a135e15d4b083832113f2300ea8

**Comment by debian-sh** [comment]
<input type="hidden" name="redirect_success" value="/">

**Comment by debian-sh** [comment]
```html
<input type="hidden" name="redirect_success" value="/">
```
