### ISSUE TITLE
Nowy module: upload plików na serwer

### ISSUE THREAD

**Issue by debian-sh** [Sealious/Sealious#115]
Moduł dający możliwość wysyłania plików na serwer. Sam serwer musiałby być przygotowany na odbieranie predefiniowanych plików, np. o określonej strukturze, nazewnictwie, wielkości oraz wyspecyfikowany mechanizm który pozwoli dodawać hiperłącze do określonego zasobu. Zakładam następującą idee uploaduje plik na serwer wraz z różnymi danymi do RESTa. Tworzy się zasób o określone strukturze tak jak dotychczas definiujemy własny `resource_type`. Określamy w JSONie typ przyjmowanego pliku, ustawiamy adres odbioru. Po wysłaniu danych POSTem tworzy się nowy zasób z url'em do określonego pliku. Deweloperowi można dać możliwość definiowania co ma być akceptowalne, np. przyjmuj każdy plik o ścisłej nazwie (regex) jeśli rozszerzenie to png i wielkość nie przekracza 2MB wtedy przyjmij zapytanie. W sieci istnieje wiele rozwiązań na upload plików, lecz np. w moim osobistym przypadku każda próba implementacji do swoich projektów takich tworów kończyła się niepowodzeniem. Myślę, że temat dla dużego grona deweloperów jest problematyczny.

Przykładowa struktura zasobu, który ma odnośnik do załadowanego pliku:
```json
{
"title": "sealious-name",
"owner_id": 0,
"id": 1,
"access_mode": "private",
"file_url" : "http://..."
},
```

**Comment by debian-sh** [comment]
Na jakim etapie jesteśmy?

**Comment by simplypixi** [comment]
Pliki się zapisują ;)

**Comment by debian-sh** [comment]
Potrzebowałbym przykładu jak mogę tę obsługę wykorzystać. :)



*Pozdrawiam,Arkadiusz Wieczorek*
Front-end developer
arkadiusz.ikleks.pl

**Comment by simplypixi** [comment]
Jeszcze branch nie jest "domergowany", ale możesz sobie zerknąć jak to
wygląda w base-chipsach.

Przykład wczytania plików z formatki masz tutaj:
https://github.com/Sealious/sealious-base-chips/blob/issue%23139_file_manager/use/channel.www_server.js

files - zawiera dane na temat plików zapisanych w domyślnej lokalizacji
("uploaded_files")
files2 - zawiera dane na temat plików zapisanych w dowolnej innej
lokalizacji

Używasz, której opcji chcesz. ;P
W odpowiedzi dostajesz prawdziwą nazwę pliku, rozszerzenie oraz ścieżkę
dostępu do pliku.

Najlepiej zaciągnij sobie wszystkie branche file_manager i przetestuj. Póki
co nie działa na rozproszonym dlatego nie robiłem pull requesta.

No i zapraszam tutaj: https://github.com/Sealious/Sealious/issues/139 :P

**Comment by debian-sh** [comment]
ok dzięki dzisiaj przejrzę jeśli będę miał problem to się zgłoszę :)
