### ISSUE TITLE
Poprawa struktury aplikacji

### ISSUE THREAD

**Issue by groovy354** [Sealious/Sealious#117]
Na spotkaniu doszliśmy do wniosku, że sealious nie powinien być narzędziem uruchamianym z poziomu cmd, ale pakietem npm-owym, który aplikacje mogą require'ować. Sealious powinien z pliku `package.json` sprawdzać, które pakiety z "dependencies" są modułami sealiousowymi (resolvując ich ścieżkę i testując obecność pliku `sealious-module.json`. 
Przykładowy kod aplikacji, która jest oparta na Sealiousie:
```js
var Sealious = require("sealious");

var app = new Sealious.App(__dirname+"/package.json");
app.config({/*konfiguracja*/});

app.start("local");
```

**Comment by theadimar21** [comment]
(myślałem że tak ma być od początku) Dobry pomysł.

W dniu 26 marca 2015 13:53 użytkownik Kuba Orlik <notifications@github.com>
napisał:

**Comment by debian-sh** [comment]
Dzisiaj uzgodniliśmy taką formę, myślę że to świetny krok

**Comment by theadimar21** [comment]
Podczas sprawdzania przykładowej apki w trybie rozproszonym pojawiło się kilka uwag/blędów:

**REST**
 * ```POST /api/v1/form_entry``` - będąc niezalogowanym wyświetla się ```not logged in```, ale status jest ```200```
 * podczas próby zarejestrowania istniejącego użytkownika warstwa biznesowa wywala stos nie przekazując komunikatu o błędzie

**Struktura**

```JavaScript
var app = new Sealious.App(__dirname+"/package.json", mode, layer_name);

var www_server = app.ChipManager.get_chip("channel", "www_server");

var form_entry = new Sealious.ChipTypes.ResourceType("form_entry");	

form_entry.add_fields([
	{name: "first-name", type: "text", required: true},
	{name: "last-name", type: "text", required: true},
	{name: "PESEL", type: "text", required: true}
])

var rest = app.ChipManager.get_chip("channel", "rest");
```
Za bardzo nam się z tego robi *JAVA*Script, jak to Kuba zauważył. Dla osoby nie będącej w temacie taki odwoływanie się do poszczególnych metod jest bardzo niejasne. Aczkolwiek domyślam się, że to jest kwestia na inne issue, bądź nawet na osobną refaktoryzację.

**Nazewnictwo**
Nazywanie plików, w których deklarujemy dany chip i plików, w których te chipy przekształcamy do naszych potrzeb jest nieścisłe i prowadzi do konfuzji.

**Comment by groovy354** [comment]
Dodatkowo:
metoda App.start zwraca Promise'a, który ani się nie resolvuje, ani nie
rzuca błędu, co utrudnia pisanie testów

-----
Kuba

2015-04-09 18:16 GMT+02:00 theadimar21 <notifications@github.com>:

**Comment by theadimar21** [comment]
##Do poprawki##
###Tryb lokalny###
 * status ```500``` na ```POST /login``` przy próbie zalogowania nieistniejącego użytkownika,
 * status ```500``` na ```POST /api/v1/users``` przy próbie zarejestrowania istniejącego użytkownika,
 * status ```200``` na ```GET /api/v1/users/{id}``` przy podaniu ```{id}``` nieistniejącego użytkownika,
 * status ```500``` na ```GET /api/v1/users/me``` będąc zalogowanym,
 * status ```500``` na ```GET /api/v1/users/me``` będąc niezalogowanym,
 * status ```200``` na ```DELETE /api/v1/users``` - osobne issue: #123
 * zawiecha i wysypanie (czerwonego o.o) stosu na ```PUT /api/v1/users/me```  - osobne issue: #124
 * status ```500``` na ```POST /api/v1/users/me``` będąc niezalogowanym

###Tryb rozproszony###
Wszystkie powyższe.

**Comment by theadimar21** [comment]
https://github.com/Sealious/sealious-base-chips/commit/177c0813990afde45504a6af2ab8975b7a3c9011
