### ISSUE TITLE
Znaleźć i zaimplementować pakiet do logowania informacji o stanie Sealiousa do konsoli

### ISSUE THREAD

**Issue by groovy354** [Sealious/Sealious#118]
Trzeba znaleźć ciekawszą alternatywę dla `console.log` :)
Należy znaleźć pakiet npm, który zapewnia:
* kilka poziomów logowania, np. 0 - żadnego logowania, 1 - tylko błędy, 2 - wszystkooo
* fajnie by było, gdyby pakiet ten opcjonalnie automatycznie wypisywał nazwę i linijkę pliku, w którym rzucany jest dany komunikat (ale to zawsze można dokodzić ręcznie)

**Comment by simplypixi** [comment]
https://www.npmjs.com/package/log

-----Wiadomość oryginalna-----
Od: "Kuba Orlik" <notifications@github.com>
Wysłano: ‎2015-‎04-‎04 11:54
Do: "Sealious/Sealious" <Sealious@noreply.github.com>
Temat: [Sealious] Znaleźć i zaimplementować pakiet do logowania informacji o stanie Sealiousa do konsoli (#118)

Trzeba znaleźć ciekawszą alternatywę dla console.log :)
Należy znaleźć pakiet npm, który zapewnia:
kilka poziomów logowania, np. 0 - żadnego logowania, 1 - tylko błędy, 2 - wszystkooo 
fajnie by było, gdyby pakiet ten opcjonalnie automatycznie wypisywał nazwę i linijkę pliku, w którym rzucany jest dany komunikat (ale to zawsze można dokodzić ręcznie)

**Comment by groovy354** [comment]
O, super - to teraz trzeba go zaimplementować :)

**Comment by theadimar21** [comment]
Znalazłem lepszą alternatywę: ```winston```.

**Comment by theadimar21** [comment]
Logger po dostaniu Sealious.Error powinien decydować czy ma wypisać error czy warning czy cokolwiek innego (lazyseal? :D :D :D :D :D)

**Comment by debian-sh** [comment]
Powinniśmy też wypisywać w logach informację o zmianie zasobu z podaniem konkretnego id. Aktualnie pokazujemy że coś się stało - poszła metoda PUT, ale nie wiemy jakie było id zasobu.

```javascript
2015-04-27 18:16:37.379 - info: PUT /api/v1/places/{id}
2015-04-27 18:16:40.423 - info: PUT /api/v1/places/{id}
2015-04-27 18:16:45.133 - info: PUT /api/v1/places/{id}
```

**Comment by theadimar21** [comment]
Fix'd
