### ISSUE TITLE
Interfejs webowy dla dewelopera aplikacji

### ISSUE THREAD

**Issue by debian-sh** [Sealious/Sealious#119]
Jest pomysł na interfejs webowy na dodatkowym public'u, w którym deweloper aplikacji będzie miał następujące możliwości:
- przeglądanie i analiza logów aplikacji,
- raportowanie logów serwera,
- dostęp do shella?
- proste zarządzanie bazą danych (users i zdefiniowane zasoby)
- zarządzanie REST API

**Comment by theadimar21** [comment]
Popieram. +1

W dniu 9 kwietnia 2015 12:12 użytkownik Arkadiusz Wieczorek <
notifications@github.com> napisał:

**Comment by debian-sh** [comment]
Do głowy wpadł mi rysujący się graf z wszystkimi zależnościami :)

**Comment by groovy354** [comment]
It will be realized in https://github.com/Sealious/sealious-www-server/issues/34
