### ISSUE TITLE
Referencje

### ISSUE THREAD

**Issue by Delfinek** [Sealious/Sealious#126]
Referencja nie powinna być typem pola, poniewaź zawiera za dużo logiki innego typu niż "is proper value". Jest pomysł, żeby referencja była czymś takim jak pole, tzn. żeby na zasobie wywołać metodę "add_reference", tak jak teraz mamy "add_fields".

Przykład:
Chcemy, żeby pewien zasób przechowywał dane do wystawiania faktur. Część faktur wystawiamy firmom, część osobom fizycznym. Jak sobie z tym poradzić?
Chcielibyśmy, żeby deklaracja referencji wyglądała następująco:
```
form_entry.add_references([
   { name: "dane_do_faktury",
     allowed_types: ["dane_osoby_fizycznej", "dane_firmy"]
}
```
Dobrym pomysłem jest założenie, że referencja może być wielokrotna - tzn. definiowanie i postowanie tablic referencji, a nie pojedynczych referncji.
```
POST 
{ "filed": "value",
   "key": "value2",
"dane_do_faktury":[{
   type: "dane_osoby_fizycznej"
   data:{....}
}]
```

Taki POST na app/form_entry powinien utowrzyć form_entry z polami field i key i referencją do zasobu typu "dane_osoby_fizycznej" i treści "data".

**Comment by groovy354** [comment]
Dodatkowo myślę, że "name" w deklaracjach referencji, pól i asocjacji w danym typie zasobu powinno zostać zmienione na "key". Dany typ zasobu miałby wtedy tablicę `keys`, w której będą przechowywane wszystkie klucze, na które można mu wpisywać wartości - niezależnie od tego, czy jest to pole aotmowe, asocjacja, czy referencja. Jakieś sprzeciwy?

**Comment by groovy354** [comment]
Hmm w trakcie implementowania referencji nie natknąłem się na nic, co by przymuszało uczynienie z nich jakiegoś osobnego bytu - myślę, że Referencje mogą być po prostu typem pola.

**Comment by groovy354** [comment]
Zrobione - pull request czeka - https://github.com/Sealious/Sealious/pull/142
