### ISSUE TITLE
Pokazywanie tylko strony z autoryzacją, gdy nie ma uprawnień do oglądania strony startowej

### ISSUE THREAD

**Issue by modliszka** [Sealious/Sealious#129]
Otwieranie aplikacji powinno pokazywać tylko i wyłącznie stronę startową (jeśli nie masz uprawnień, nie jesteś zalogowany). Obecnie wczytywana jest najpierw główna strona aplikacji, a potem następuje przekierowanie na stronę z autoryzacją.

+możliwość własnej konfiguracji przekierowań takich stron

**Comment by theadimar21** [comment]
Wina jQuery. Trzeba jakoś inaczej zaprogramować przekierowania.

**Comment by groovy354** [comment]
Pracuje nad tym - ten issue zostanie rozwiązany za pomocą kontekstów :)

**Comment by groovy354** [comment]
Problem będzie rozwiązany w okolicach 0.4.0 :)
