### ISSUE TITLE
[Core_service] File Manager 

### ISSUE THREAD

**Issue by simplypixi** [Sealious/Sealious#139]
Trzeba utworzyć service "file_manager" korzystający z channel "uploader". Parka ta ma za zadanie obsługę plików wysyłanych za pomocą formularza.

**Comment by simplypixi** [comment]
http://azure.microsoft.com/pl-pl/documentation/articles/storage-nodejs-how-to-use-blob-storage/

**Comment by simplypixi** [comment]
http://stackoverflow.com/questions/16245767/creating-a-blob-from-a-base64-string-in-javascript

**Comment by simplypixi** [comment]
https://gist.github.com/fupslot/5015897

**Comment by simplypixi** [comment]
Stan file_managera na dzisiaj:
- zapisywanie plików w domyślnej ("uploaded_files") lub dowolnej lokalizacji
- zmiana nazwy pliku
- zwracanie danych plików wrzuconych przez użytkownika
Póki co działa tylko w lokalnym.

**Comment by groovy354** [comment]
Super!
Czy pliki wysłane na serwer zachowują nazwę i rozszerzenie?

**Comment by simplypixi** [comment]
Tak. ;)
Na serwerze plik trzymany jest uuid jako nazwą. W bazie trzymane są szczegółowe dane na temat tego pliku. Tzn. oryginalna nazwa, rozszerzenie i ścieżka do pliku. ;)
