### ISSUE TITLE
Nomenklatura - zmienić "moduł sealiousowy" na "plugin sealiousowy"

### ISSUE THREAD

**Issue by groovy354** [Sealious/Sealious#144]
Wyrażenie "moduł sealiousowy" jest mylące ze względu na podobieństwo do "moduł node'owy". Proponuję rozwiązać ten problem poprzez zamienienie wyrażenia "moduł sealiousowy" na "pllugin sealiousowy".
Zmiany te muszą być widoczne zarówno w dokumentacji, jak i w kodzie.

**Comment by theadimar21** [comment]
Moduł node'a - noduł,
moduł Sealiousa - soduł.

Fixed :D

W dniu 26 kwietnia 2015 19:47 użytkownik Kuba Orlik <
notifications@github.com> napisał:

**Comment by groovy354** [comment]
Teraz jeszcze tylko zaimplementować ;)

**Comment by debian-sh** [comment]
Popieram jakoby module i plugin są rozszerzeniami, lecz określenie module może być mylące z pakietami pobieranymi z npm'a. +1

**Comment by groovy354** [comment]
This issue was resolved a long time ago.

**Comment by theadimar21** [comment]
Czyli "soduł" jest nicht gut? :(

2015-09-01 11:55 GMT+02:00 Kuba Orlik <notifications@github.com>:

**Comment by debian-sh** [comment]
Ja, ist nicht gut! :)



*Pozdrawiam,Arkadiusz Wieczorek*
Front-end developer
co-founder Placetag.pl
github.com/debian-sh
