### ISSUE TITLE
Logowanie informacji o nowej i bieżącej wersji Sealiousa oraz sealious-base-chips w konsoli

### ISSUE THREAD

**Issue by debian-sh** [Sealious/Sealious#145]
Podczas startu aplikacji moglibyśmy wyświetlać bieżącą wersję oraz dostępną, najnowszą jeśli takowa istnieje - jakiś szybki GET rzucający informację na output dla Sealious oraz sealious-base-chips. 

Dodatkowo opcjonalne wyłączenie tej funkcji w jakimś pliku konfiguracyjnym + możliwość wywołania skryptu aktualizującego pakiety ad-hoc.

**Comment by groovy354** [comment]
Nie powinniśmy imo wychodzić z założenia, że Sealious jest wykonywany w środowisku z dostępem do Internetu - więc jakby taka funkcjonalność miała być dołączona, to  powinna być niedomyślna

**Comment by theadimar21** [comment]
Eksperymentuje z pakietem ```npm-check```, dla testów stworzyłem w katalogu głównym Sealiousa plik ```test.js```:

```JavaScript
var npmCheck = require('npm-check');

npmCheck()
.then(function(data){
	console.log(data);
});
```

Niestety czas wykonywania tej funkcji jest całkiem długi, a chyba nie o to chodzi (*chyba*), tak więc poszukam czegoś innego

**Comment by groovy354** [comment]
Być może warto będzie najpierw wczytać numer wersji z package.json (`require.resolve("sealious")`) a potem zrobić jedno szybkie zapytanie http do npm-a (w kodzie źródłowym npm-a znalazłem, że wystarczy zrobić zapytanie na `registry.npmjs.org/sealious` :) ) i porównać wersje

**Comment by debian-sh** [comment]
Skoro wychodzimy z założenia, że Sealious nie jest odpalany w środowisku z dostępem do sieci. To powinniśmy rzucać komunikatem, że nie możemy sprawdzić wersji sealious'a z powodu braku dostępu do sieci.

```javascript
arkadiusz@arkadiusz-ThinkPad-X200:~/Dokumenty/WMI-6/DPRO/Placetag/placetag-app$ sudo node .
[sudo] password for arkadiusz: 
15:28:18.474 - info: Initializing modules...
	 base_chips ...
15:28:19.542 - info: Modules initialized!
15:28:19.562 - info: service_name: user_manager
15:28:19.563 - info: service_name: metadata_manager
15:28:19.585 - info: SERVER RUNNING: http://arkadiusz-ThinkPad-X200:80

events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: getaddrinfo ENOTFOUND registry.npmjs.org
    at errnoException (dns.js:44:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:94:26)
```

**Comment by theadimar21** [comment]
Good point.

**Comment by debian-sh** [comment]
Pull request https://github.com/Sealious/Sealious/pull/159

Przetestowane! Nie można zrobić tego przez `try...catch` nie jest w stanie łapać tego błędu, trzeba nasłuchiwać emitu. Pierwsze uruchomienie sealious-example-app z dostępem do sieci, drugie bez. Aplikacja pomimo błędu działa.

![image](https://cloud.githubusercontent.com/assets/5663277/7505353/e1ce150e-f451-11e4-8fab-30d99b7f06d2.png)

**Comment by theadimar21** [comment]
A co jeśli wysypie się jakiś inny error? Sprawdziłeś np. dla EACCES albo
EADDRINUSE?

W dniu 7 maja 2015 00:46 użytkownik Arkadiusz Wieczorek <
notifications@github.com> napisał:

**Comment by debian-sh** [comment]
Cóż to za errory? Skąd one mogą się pojawić z tego get'a?
