### ISSUE TITLE
Błąd przy uruchamianiu aplikacji 

### ISSUE THREAD

**Issue by modliszka** [Sealious/Sealious#149]
Taki błąd zwraca mi konsola przy próbie uruchomienia aplikacji Placetag. Robiłam update już, koniec końców mogę usunąć node_modules i zainstalować na nowo, no ale to nie będzie rozwiązanie problemu.

	E:\STUDIA III rok II sem\PRI\Placetag\placetag-app\package.json
	10:24:11.157 - info: Initializing modules...
			 base_chips ...
	{ [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }

	js-bson: Failed to load c++ bson extension, using pure JS version
	10:24:21.341 - info: Modules initialized!
	E:\STUDIA III rok II sem\PRI\Placetag\placetag-app\node_modules\sealious\lib\chip-types\resource-type-field.js:9
			this.type = new type_constructor();
						^
	TypeError: undefined is not a function
		at ResourceTypeField (E:\STUDIA III rok II sem\PRI\Placetag\placetag-app\node_modules\sealious\lib\chip-types\resource-type-field.js:9:14)
		at add_field (E:\STUDIA III rok II sem\PRI\Placetag\placetag-app\node_modules\sealious\lib\chip-types\resource-type.js:20:22)
		at add_fields (E:\STUDIA III rok II sem\PRI\Placetag\placetag-app\node_modules\sealious\lib\chip-types\resource-type.js:31:9)
		at Object.<anonymous> (E:\STUDIA III rok II sem\PRI\Placetag\placetag-app\main.js:8:8)
		at Module._compile (module.js:460:26)
		at Object.Module._extensions..js (module.js:478:10)
		at Module.load (module.js:355:32)
		at Function.Module._load (module.js:310:12)
		at Function.Module.runMain (module.js:501:10)
		at startup (node.js:129:16)
		at node.js:814:3

Main.js:

	var path = require("path");
	var Sealious = require("sealious");

	Sealious.init("local");
	var www_server = Sealious.ChipManager.get_chip("channel", "www_server");

	var places = new Sealious.ChipTypes.ResourceType("places");	
	places.add_fields([
		{name: "title",					type: "text"},
		{name: "description",			type: "text"},
		{name: "street",				type: "text"},
		{name: "city",					type: "text"},
		{name: "longitude",				type: "float", required: true}, //52 dlugosc
		{name: "latitude",				type: "float", required: true}  //16 szerokosc
	])

	var rest = Sealious.ChipManager.get_chip("channel", "rest");
	rest.add_path("/api/v1/places", "places");

	www_server.static_route(path.resolve( __dirname, "./public"), "");
	Sealious.start();
Jakieś pomysły co i gdzie może być źle?

**Comment by groovy354** [comment]
Wydaje się, że nie masz zainstalowanego jakiegoś field_type'a. Być może
powinnaś zaktualizować base-chips?

**Comment by modliszka** [comment]
Hmm.. działa teraz, ale użyłam chyba wszystkie komendy, jakie mi przyszły do głowy. xD Tak dla pewności, czym aktualizujemy npm?
Standardowo robiłam `npm update` i `npm install`. Czy muszę jednak wszystko osobno robić, tzn. `npm update sealious-base-chips` i `npm install sealious-base-chips`? Bo wtedy właśnie mi chyba zadziałało.

**Comment by debian-sh** [comment]
Ja robię update później install na obu pakietach

Sent with AquaMail for Android
http://www.aqua-mail.com

**Comment by debian-sh** [comment]
Tutaj chyba wszystko zamykam! ;)
