### ISSUE TITLE
Usunąć zależność UserManagera od sealious-base-chips

### ISSUE THREAD

**Issue by groovy354** [Sealious/Sealious#156]
Aktualnie UserManager mocno polega na istnieniu typu zasobu "user" (który jest chipem w sealious-base-chips). Sealious powinien być samodzielny, tzn nie posiadać w Corze żadnych chipów.
Sprawę tę należy rozwiązać tak:
* trzeba znaleźć osobny sposób na przechowywanie danych o autoryzacji użytkowników, całkowicie rozłączny ze sposobem, w jaki przechowujemy informacje o zasobach. Myślę, że powinna to być jakaś wydajna baza typu klucz-wartość (trzeba znaleźć jakąś, która ładnie współpracuje z Nodem)
* dane o username'ach i hasłach przechowujemy w tej nowej bazie
* jeżeli chcemy rozszerzyć obiekt "user" o nowe atrybuty, to musimy stworzyć nowy *typ zasobu* i wywołać metodę `Sealious.UserManager.ExtendUser("nazwa_teg_typu_zasobu")`

**Comment by debian-sh** [comment]
Jeśli chodzi o wydajną bazę danych klucz-wartość to może http://redis.io/

**Comment by groovy354** [comment]
Redis nadawałby się tylko do przechowywania informacji o sesji - nie ma w nim możliwości szukania po zawartości.

**Comment by debian-sh** [comment]
Myślałem jeszcze couchdb.apache.org/ ale nie mogę sprawdzić dokumentacji

Sent with AquaMail for Android
http://www.aqua-mail.com

**Comment by groovy354** [comment]
Myślę, że wybór bazy danych pozostawimy deweloperom - wystarczy tylko napisać odpowiedni chip typu datastore :)

**Comment by groovy354** [comment]
Issue no longer valid
