### ISSUE TITLE
Koło naukowe dookoła Sealiousa

### ISSUE THREAD

**Issue by groovy354** [Sealious/Sealious#158]
Bardzo spodobał mi się pomysł założenie koła naukowego dookoła Sealiousa - chciałbym zebrać informacje nt. jak się za to zabrać.
Co myślicie o założeniu Kola Naukowego Sealious? :)
Polu, czy dała byś radę ogarnąć ten temat?

**Comment by simplypixi** [comment]
Dla mnie brzmi spoko. ;)

Mariusz Wójcik
tel. 507-386-287

Napisz wiadomość >> <pixiproject@gmail.com>
Przejdź do portfolio >> <http://simplypixi.portfoliobox.me/projects>
[image: 2]
<http://oferia.pl/wykonawca/pixel93/323171?utm_source=powiad&utm_medium=email&utm_campaign=sygnatura_mail>

W dniu 5 maja 2015 17:22 użytkownik Kuba Orlik <notifications@github.com>
napisał:

**Comment by debian-sh** [comment]
Ja również jestem za! Może pozyskamy zdolne jednostki, mniej zdolne nauczą się JSa i paru innych rzeczy.

**Comment by theadimar21** [comment]
+1

**Comment by debian-sh** [comment]
Temat chyba umarł hm?

**Comment by groovy354** [comment]
Myślę, że zajmiemy się tym na praktykach :)

**Comment by debian-sh** [comment]
Nie lepiej poświęcić ten czas na jakieś backendy? :)

**Comment by groovy354** [comment]
Będziemy robić duże liości naraz rzeczy :)

-----
Kuba

**Comment by Delfinek** [comment]
Po co Sealiusowi koło naukowe?
* żeby docierać do nowych osób - studentów, którzy chcieliby rozwijać projekt
* żeby mieć stałe miejsce i porę spotkań na wydziale

Wydaje się, że obydwa cele możemy osiągnąć nie zajmując się wszystkimi formalnościami związanymi z zakładaniem koła - wystarczy dogadać się z jakimś pracownikiem naukowym (być może do czegoś będzie potrzbna zgoda dziekana). Koła naukowe są zwykle organizują konferencje, na które zdobywają  środki finansowe - tego nie potrzebujemy. Na WMI funkcjonuje koło naukowe Matematyki i Informatyki Stosowanej, myślę że jeśli będziemy potrzebować załatwić coś formalnie jako koło naukowe z chęcią nam pomogą.
http://mis.wmi.amu.edu.pl/

**Comment by groovy354** [comment]
OK, case dismissed
