### ISSUE TITLE
REST - Status 201 Created

### ISSUE THREAD

**Issue by debian-sh** [Sealious/Sealious#161]
Pomyliłem repozytoria, tutaj jest odpowiednie miejsce https://github.com/Sealious/sealious-base-chips/issues/24

**Comment by groovy354** [comment]
Czy znasz jakiekolwiek praktyczne zastosowanie dla tego nagłówka?

**Comment by debian-sh** [comment]
Chociażby dlatego, że gdy dodamy nowe zasób to nie znamy jego id. Aby dowiedzieć się jaki jest jego id musimy robić GETa na cały zasób a nie na konkretny dokument. Np. natychmiastowe wyświetlenie w danym widoku. Pracujemy nad wersją androidową dla Placetaga i bardzo ułatwiłoby nam to prace. Jeśli nie możemy tego dodać to proszę Cię o opisanie, jak mogę dla własnych potrzeb to wdrożyć. Ale myślę, że jest to przydatny feature.

**Comment by groovy354** [comment]
Id utworzonego zasobu jest zawarte w JSONie, który zwraca POST

-----
Kuba

2015-05-11 10:41 GMT+02:00 Arkadiusz Wieczorek <notifications@github.com>:

**Comment by debian-sh** [comment]
Ok nie zauważyłem bo wcześniej mieliśmy `[Object object]`
