### ISSUE TITLE
Przenieść zarządzanie sesją do UserManagera

### ISSUE THREAD

**Issue by theadimar21** [Sealious/Sealious#162]

**Comment by groovy354** [comment]
Ostatecznie przy tworzeniu kontekstów i strategii dostępu przeniosłem SessionManager do kanału HTTP. Ponieważ:
Wszystkie metody core-service'ów są wrażliwe na *kontekst*. Kontekst zawiera w sobie informacje o id użytkownika, który dokonuje zapytania, timestampie i adresie ip. Stwierdzenie w imieniu którego użytkownika jest dokonane dane zapytanie i stworzenie odpowiedniego obiektu kontekstu jest zadaniem kanału.
