### ISSUE TITLE
Problemy wydajnościowe dla dużej ilości zasobów w bazie danych

### ISSUE THREAD

**Issue by theadimar21** [Sealious/Sealious#164]
Dodałem kod do tworzenia 1.000.000 (milion) nowych zasobów, odpowiedź:
```
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory
Aborted (core dumped)
```

Postanowiłem dodawać ich trochę mniej, najpierw 1000, potem 10,000 i w końcu 100,000, odpowiedź:
```
 Resources:
    ✓ should not create a new resource (38ms)
    ✓ should create a new resource
    1) should create 100,000 resources
    ✓ should get data about the resource (106ms)
    ✓ should delete the resource (108ms)
    ✓ should update the resource (197ms)
    2) should list resources by type
    ✓ should get resource type signature (schema)

  Users:
    ✓ should create a new user (311ms)
    ✓ should get data about all users (317ms)
    ✓ should update user data (369ms)
    ✓ should delete the user (192ms)
    ✓ should not find a user (108ms)
    ✓ should find a user (206ms)


  12 passing (37s)
  2 failing

  1) Resources: should create 100,000 resources:
     Error: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.
      at test.js:62:5

  2) Resources: should list resources by type:
     Error: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.
```
Ensurowałem się, że ```done() callback``` jest dodany do funkcji.

Obecnie w bazie znajduje się ok. 300,000 zasobów przez co wywala error przy ```should list resources by type``` i opóźnia wykonywanie innych metod.

**Comment by theadimar21** [comment]
Być może pakowanie wszystkiego do bazy jakos ```resource``` nie jest takim pomysłem, czas wykonywania zapytań dla userów dostał trochę po pysku tylko dlatego, że dodano wiele zasobów, co nie powinno być ze sobą powiązane.

**Comment by groovy354** [comment]
Hmm dużym problemem jest tutaj fakt, że userzy sa trzymani w kolekcji "resources". Myśłę, że jeżeli będziemy trzymali userów w innej kolekcji, to nie spadnie nam wydajność (przynajmniej nie tak drastycznie)

**Comment by groovy354** [comment]
Do poczytania - http://docs.mongodb.org/manual/tutorial/manage-the-database-profiler/

**Comment by groovy354** [comment]
Być może warto też będzie popracować nad data modellingiem - http://docs.mongodb.org/manual/data-modeling/

**Comment by modliszka** [comment]
Przetestowałam na przykładowej apce - wstawienie 100.000 wierszy kodem:

    console.time('insertData');
	var insertData = new function(){
		var all_promises = [];
		console.log("przed wstawianiem");

		for(var i=0; i<1000; i++){
			for(var j=0; j<100; j++){
				var current_promise = ResourceManager.create({},"person",{name: "xx"+i, age: i+j});
				all_promises.push(current_promise);
			}
		}

		console.log("po wstawianiu");
		//1000x100 77883ms
		Promise.all(all_promises).then(function(){
			console.timeEnd('insertData');
		})
	};

Co zajęło 77883ms, a wyszukanie przykładowego wiersza:

	console.time('findRecord');
	var findRecord = new function(){
		var x = ResourceManager.find({},{'name': "xx2", 'age': 10},"person").then(function(results){
			console.log(arguments);			
		});
	};
	console.timeEnd('findRecord');

Zajęło 9ms. Nie widzę więc problemu w limicie czasu dla powyższych operacji. Wstawianie dużej ilości wierszy chcąc nie chcąc musi trochę potrwać. ;)
