### ISSUE TITLE
Problemy stabilnościowe z sealiousem (Placetag.pl)

### ISSUE THREAD

**Issue by debian-sh** [Sealious/Sealious#165]
Serwer sam padł, nic nie wynika z logów. Ostatnio mieliśmy ogromną ilość logowań. Myślę, że warto przetestować tworzenie sesji czy tam się w pewnym momencie coś nie dzieje.

**Comment by groovy354** [comment]
czy korzystałeś z `nohup`?

**Comment by debian-sh** [comment]
heh, tak nic z niego nie wynika

**Comment by groovy354** [comment]
jaka jest ostatnia linijka nohupa?

**Comment by debian-sh** [comment]
oj no mówię, że nic bo był GET `11:05:40.528 - info: GET /api/v1/places - success!`

**Comment by groovy354** [comment]
wyślij mi plik nohupa na mejla :)

**Comment by debian-sh** [comment]
*Pozdrawiam,Arkadiusz Wieczorek*
Front-end developer
arkadiusz.ikleks.pl

**Comment by debian-sh** [comment]
Na razie zamykam jeśli coś padnie to zrobię re-open.
