### ISSUE TITLE
Nieintuicyjne logi z serwera

### ISSUE THREAD

**Issue by debian-sh** [Sealious/Sealious#166]
Przeglądając logi z serwera nie byłem w stanie ustalić kiedy odnotowano logowanie - godzina dużo nie mówi :) Może timestamp zamiast godziny, albo dopisywanie w logach o godzinie 00:00 nowej daty.

**Comment by groovy354** [comment]
Hmm w aktualnej wersji printujemy czas z dokładnością co do setnej sekundy - czy logi, o których mówisz to logi z Sealiousa >=0.3.6?

**Comment by debian-sh** [comment]
Problemem jest to, że nie znamy dnia outputu dla loga tzn. np.
`12:03:37.273 - info: Killing session:  2750b38c4aa651b1bfda621290b31f3ca22c2363
`
ok zabito sesję, ale to było dzisiaj, wczoraj? Kiedy :)

Mam dwa pomysły na rozwiązanie:
- zamiast wyświetlać dokładną godzinę podać timestamp, słabo czytelne ad-hoc dla developera w terminalu
- lepsza opcja o północy wypisywać na output coś takiego

`00:00:00.000 - info: Today is Thu May 21 2015 00:00:00 GMT+0200 (CEST)`

**Comment by groovy354** [comment]
Logi idące do plików (Sealious ma taką funkcję) zawierają datę wraz z dniem i miesiącem, niestety próbowałem włączyć logi za pomocą ConfigManagera i coś tam nie klika, trzeba to naprawić - póki co możesz włączyć logi ręcznie, wpisując ścieżkę do pliku logów do atrybutu "logger_file", w pliku `logger.js:20`

**Comment by groovy354** [comment]
Logger został ulepszony i poprawiony w międzyczasie - zamykam :)
