### ISSUE TITLE
VersionChecker - crashes the app if npm registry query fails

### ISSUE THREAD

**Issue by groovy354** [Sealious/sealious#180]
core.js, line 22:
```js
var sealious_npm = JSON.parse(body);
```

NPM registry's http API might be a little bit unpredictable in the future, and return empty body for some queries. If it so happens, then the above line will crash the app. We need to handle that elegantly.

**Comment by debian-sh** [comment]
What do you suggest? In my case I turned off `check_request` function.

**Comment by groovy354** [comment]
Well, a simple try/catch statement on core.js:22 would fix it imo

**Comment by debian-sh** [comment]
Ok, take care of this? Does the error still occur?

**Comment by groovy354** [comment]
The npm registry has been fixed, but only for now - so this error might appear in the future and we need to be ready for it (i.e. handle it well)

**Comment by groovy354** [comment]
Fixed in ed23c4f009
