### ISSUE TITLE
Make datastore's methods' asynchronicity optional

### ISSUE THREAD

**Issue by groovy354** [Sealious/sealious#181]
Currently all methods of a datastore have to return a Promise. To ease datastore development, we should make it optional - so datastore methods can either `return` or `Promise.resolve` their values

**Comment by debian-sh** [comment]
Good point :)

**Comment by groovy354** [comment]
This would require a change in the database chip type declaration API - so it's going to appear in 0.7

**Comment by groovy354** [comment]
We'll be tracking this task on [our trello board](https://trello.com/c/j23O1b21/7-make-datastore-s-methods-asynchronicity-optional)
