### ISSUE TITLE
MongoDB - crashes the app if machine doesn't have mongo

### ISSUE THREAD

**Issue by debian-sh** [Sealious/sealious#182]
I think we should catch this error more elegantly. For example "Your machine doesn't have required mongodb package" for linux machines. However if developer sets `"datastore_chip":"mongo"`  it probably is sure that this package is already installed. What do you think?

```bash
/home/zbox/Projects/Placetag/placetag-app/node_modules/sealious/lib/base-chips/datastore.mongo.js:45
				db = mongoClient.db(config.db_name);
				                ^
TypeError: Cannot read property 'db' of null
    at /home/zbox/Projects/Placetag/placetag-app/node_modules/sealious/lib/base-chips/datastore.mongo.js:45:21
    at /home/zbox/Projects/Placetag/placetag-app/node_modules/sealious/node_modules/mongodb/lib/mongodb/mongo_client.js:99:20
    at /home/zbox/Projects/Placetag/placetag-app/node_modules/sealious/node_modules/mongodb/lib/mongodb/db.js:286:18
    at /home/zbox/Projects/Placetag/placetag-app/node_modules/sealious/node_modules/mongodb/lib/mongodb/db.js:365:7
    at process._tickDomainCallback (node.js:381:11)
```

**Comment by groovy354** [comment]
I think it would be a good idea to test `if(mongoClient==null)` and display a more readable error if so. Assigning DX label :)

**Comment by theadimar21** [comment]
What if the user simply misspells the name of his DB? :)

2015-08-26 7:47 GMT+02:00 Kuba Orlik <notifications@github.com>:

**Comment by theadimar21** [comment]
Not the DB name, but the datastore name, pardon me. <grabs a cup of
delicious tea and puts his monocle on>

**Comment by debian-sh** [comment]
Then framework should inform developer about inadequate datastore name, because properly we know  "what are have available datastores".

**Comment by theadimar21** [comment]
Then typing the datastore name in seems impractical, since you can type in
anything you want, but in fact you can only choose what's being supported.

2015-08-26 9:46 GMT+02:00 Arkadiusz Wieczorek <notifications@github.com>:

**Comment by theadimar21** [comment]
My proposition:

Right now it works like this - we define the datastore in a config file,
which Sealious reads and from this file it knows which datastore to load.

What if Sealious could just detect which datastore is used without
explicitly defining it in the config file?

**Comment by debian-sh** [comment]
Maybe good idea is to create build script/command/function which will initiates config file with chosen properties by developer.

**Comment by groovy354** [comment]
Woah woah, this error is not about missing datastore, but about wrong MongoDB db server info (like IP address and port). There are some default values for mongodb connection stored in mongodb *datastore*, namely:
```js
{
	embedded: false,
	host: 'localhost',
	port: 27017,
	db_name: 'sealious'
}
```
, as you can see in `datastore.mongo.js:14`. The connection settings can be easily overwritten using ConfigManager.

**Comment by theadimar21** [comment]
My proposition is still valid.

2015-08-27 8:04 GMT+02:00 Kuba Orlik <notifications@github.com>:

**Comment by debian-sh** [comment]
No because after installed mongodb, problem solved.

Sent with AquaMail for Android
http://www.aqua-mail.com

**Comment by groovy354** [comment]
@theadimar21 - your proposition is what is currently implemented :) You can read about it [here](https://github.com/Sealious/Sealious/blob/changes_for_nice_docs/docs/reference.md#multiple-datastores)

**Comment by theadimar21** [comment]
Hm, I can see now. Yeah, this makes more sense. But what is we could skip
even this line? What if Sealious could just check the datastore on his own,
without our input?

**Comment by groovy354** [comment]
What do you mean by "check the datastore"?

Currently if only one datastore is available, no config is necessary.

**Comment by theadimar21** [comment]
Ok, so I misunderstood. :)

2015-08-28 13:16 GMT+02:00 Kuba Orlik <notifications@github.com>:

**Comment by groovy354** [comment]
So all in all we need to catch the error and display a fitting message in console. 

I think it would benefit DX greately if the message:
* pointed the developer to a link on how to set up mongoDB on their system
* pointed the developer to alternate Sealious datastores that are easier to set up

@theadimar21, understood? :)

**Comment by theadimar21** [comment]
Understood. :)

I think implementing a class that would suggest words when misspelling
occurs would be awesome from a developer POV.

**Comment by groovy354** [comment]
I agree, but how does it relate to this issue?

**Comment by theadimar21** [comment]
Partialy. When wrong datastore is set, it would be convienient if Sealious
showed possible options. Or when it is just a typo, Sealious could say: Did
you mean X?

**Comment by groovy354** [comment]
No, this issue isn't about misspelled datastore name - it's specifically about MongoDB datastore and what happens if it tries to connect to a database that does not exist

**Comment by theadimar21** [comment]
Solved here: https://github.com/Sealious/sealious-datastore-mongo/commit/ebb4d6f16033a70a9562bedf1572708da8a708ea
