### ISSUE TITLE
Separate MongoDB and TingoDB datastore drivers to separate repositories and plugins

### ISSUE THREAD

**Issue by groovy354** [Sealious/Sealious#185]
MongoDB and TingoDB drivers are very similar in structure, but their use-cases and configuration vary dramatically. Their common parts should be exported to a separate package, and MongoDB and TingoDB should be exported as separate Sealious plugins

**Comment by debian-sh** [comment]
After changes maybe windows developers don't see anything errors about TingoDB.

**Comment by modliszka** [comment]
Done in issue#185_separate_dbs: https://github.com/Sealious/Sealious/tree/issue%23185_separate_dbs.
