### ISSUE TITLE
Technical documentation

### ISSUE THREAD

**Issue by Wewe12** [Sealious/sealious#188]
Making technical documentation with every function with return type and all possible argument.

**Comment by debian-sh** [comment]
Do you think about technical documentation as description of api or as description all codes in framework, which there aren't interesting for many developers?

**Comment by groovy354** [comment]
These two things should be separate in my opinion

**Comment by Wewe12** [comment]
I thought about something like toutorial with description for beginner developer and separatly documentation with existing methods. It might be useful when someone want to find some method, argument or parametr.

**Comment by debian-sh** [comment]
Yes it's good direction.

**Comment by groovy354** [comment]
Tracked [here](https://trello.com/c/O695rl6o/11-create-a-nice-declaration-focused-documentation-and-api-reference) now
