### ISSUE TITLE
Making a documentation of Resource Manager

### ISSUE THREAD

**Issue by Wewe12** [Sealious/sealious#189]
Making a documentation of Resource Manager

**Comment by Delfinek** [comment]
inline documentation is made on branch #40, with ??? I've marked things, that needs Kuba's explanation

**Comment by groovy354** [comment]
I've explained the uncertainties in 7ae52d5ba6c

**Comment by groovy354** [comment]
https://trello.com/c/O695rl6o/11-create-a-nice-declaration-focused-documentation-and-api-reference
