### ISSUE TITLE
Coverage tests are broken

### ISSUE THREAD

**Issue by groovy354** [Sealious/Sealious#194]
Running npm run test-coverage renders an invalid html file

**Comment by debian-sh** [comment]
Is it out of date? #203?

**Comment by groovy354** [comment]
Well, there's still no easy way to preview code coverage before pushing to the remote repository - this issue will be closed once we can check code coverage locally. It should be hard to make, it'll probably use the same modules that currect `coveralls` script uses

**Comment by debian-sh** [comment]
I see. Maybe we should be use other tool for locally coverage testing.

**Comment by groovy354** [comment]
Well, we're already using jscoverage for coveralls, so perhaps we can re-use that for local coverage testing?

**Comment by debian-sh** [comment]
Ok can you run in locally this coveralls?

**Comment by groovy354** [comment]
Done in 83b96fc1dd3b476223c
