### ISSUE TITLE
Create a script for quick & easy new version publishing

### ISSUE THREAD

**Issue by groovy354** [Sealious/sealious#196]
running

```
npm run new-patch
```

(after merging a pull-request) should:
* update patch number in package.json (with `npm version patch`)
* push the newly created tags to github (`git push --tags`)
* publish the current version on npm (with `npm publish`)

**Comment by debian-sh** [comment]
I can make bash script for new version publishing if you think about it.

**Comment by groovy354** [comment]
I think it rather should be a simple command in `scripts` section of `package.json`

**Comment by debian-sh** [comment]
I see.

**Comment by groovy354** [comment]
Done in 93ad04e2b5dbae
