### ISSUE TITLE
Add ability to add new fields for the user resource

### ISSUE THREAD

**Issue by debian-sh** [Sealious/sealious#197]

**Comment by debian-sh** [comment]
Why `resource_type.user.js` has two `username` declaration?

```js
var user = new Sealious.ChipTypes.ResourceType({
	name: "user",
	fields:[
		{name: "username", type: "text", required: true},
		{name: "email", type: "email"},
		{name: "password", type: "text", required: true},
		{name: "status", type: "text"},
		{name:"username", type:"text"}
	]
});
```

**Comment by groovy354** [comment]
Woah, that's an oversight, this shouldn't be like that. The second declaration should be deleted. Also, any future duplicate fields should be detected, I've set up an issue for that - https://github.com/Sealious/Sealious/issues/213

**Comment by groovy354** [comment]
Fixed in 098093714915

**Comment by debian-sh** [comment]
I have an idea. Developer would be extend `ResourceType: user` in `index.js`. If he won't do then `ResourceType` would have default fields only `username` and `password` otherwise `ResourceType` would have all fields which Developer adds in `index.js`.

**Comment by groovy354** [comment]
I think it's a good idea. imo this should be even possible for every resource-type, not only `user` :)

**Comment by debian-sh** [comment]
Currently we have no other resource-type hence my indication.

**Comment by groovy354** [comment]
https://trello.com/c/TtIknSXZ/13-enable-extending-resource-type-for-users
