### ISSUE TITLE
Move field-type-color to a separate repository and plugin

### ISSUE THREAD

**Issue by groovy354** [Sealious/sealious#204]

**Comment by debian-sh** [comment]
We want to create new repository for non-standard field-types?

**Comment by groovy354** [comment]
Well, there are a few options that come to my head:
* create a repository for each exotic field-type we come up with
* create one, unified repository that would contain multiple (possibly *many*) field-types
* a combination of the above solutions - create a separate repository and npm package for each field-type, but create a new npm package that would enable to install them all in bulk.

Which do you think is the best?

**Comment by debian-sh** [comment]
* the weak point (many) field-types will generate many repositories in the first case it would be ugly mess
* second option certainly wouldn't generate mess in our github page
* third option is nice, but I don't like many small repositories

I propose create one repository for all exotic field-types.

**Comment by groovy354** [comment]
> the weak point (many) field-types will generate many repositories in the first case it would be ugly mess
I think that having many repositories for an organization [is](https://github.com/github) [quite](https://github.com/angular) [common](https://github.com/facebook/), so perhaps it's not something to dread.

Currently I'm considering two options:
* create a separate repository for color field-type 
* move color field-type to the core repository

What do you think?

**Comment by debian-sh** [comment]
I would like to add this field type to the core repository. :)

**Comment by groovy354** [comment]
https://trello.com/c/8WOnlGkz/16-move-field-type-color-to-core
