### ISSUE TITLE
Document field-type's `validate_declaration` method

### ISSUE THREAD

**Issue by groovy354** [Sealious/sealious#205]

**Comment by debian-sh** [comment]
Will this method is checking declaration in all field-types?

**Comment by groovy354** [comment]
Yes. If a field-type wants to perform it's own validation, it would do so by implementing `validate_params`method

**Comment by groovy354** [comment]
https://trello.com/c/O695rl6o/11-create-a-nice-declaration-focused-documentation-and-api-reference
