### ISSUE TITLE
Create new development script for developers

### ISSUE THREAD

**Issue by debian-sh** [Sealious/Sealious#211]
This script https://github.com/Sealious/Sealious/wiki/Setting-up-Sealious-for-development is out-of-date, by that I can't write new features to Sealious. In Monday we must create new script with correctly npm links, unfortunately we are wasting time on setting development instead of write new features for Sealious. Additionally we should create test app for development compatible with new Sealious API.

**Comment by groovy354** [comment]
Done! I've updated [the  wiki](https://github.com/Sealious/Sealious/wiki/Setting-up-Sealious-for-development) and I've put the new script in the `dev-setup.sh` in newest `dev` branch.

I used Sealious/hello-world as the example app.

Let me know how it works for you, so we can close this issue :)

**Comment by debian-sh** [comment]
Ok, I will try it :)

**Comment by debian-sh** [comment]
Great job, I have two insights.

* Is it normal?
```bash
19:29:47.482 - warning: Sealious@0.5.9 - update available. Run `npm install sealious@0.5.10` to update.
```
* When I start app without `sudo`, app shuts down.

**Comment by groovy354** [comment]
> Is it normal?

Well, you must've been installing the script just when I've published a new version :)

> When I start app without sudo, app shuts down.

It's because you need sudo in order to start listening on port 80

**Comment by debian-sh** [comment]
Ok, that's all.
