### ISSUE TITLE
Misleading parameter name in Datastore configuration

### ISSUE THREAD

**Issue by Wewe12** [Sealious/sealious#216]
`Sealious.ConfigManager.set_config("datastore_chip_name", "my_datastore")`
It looks like we should change `datastore_chip_name`.

**Comment by debian-sh** [comment]
Where is execute set_config outside of main.js in user application?

**Comment by groovy354** [comment]
`set_config` is used for specific application settings. All plugins shoud use `set_default_config`

**Comment by debian-sh** [comment]
+1

**Comment by debian-sh** [comment]
It looks like in my opinion that  `datastore_chip_name` sets driver for database and `my_datastore` sets new for database.

**Comment by groovy354** [comment]
https://trello.com/c/O695rl6o/11-create-a-nice-declaration-focused-documentation-and-api-reference
