### ISSUE TITLE
Use Javascript's prototype chain to implement field-type inheritance

### ISSUE THREAD

**Issue by groovy354** [Sealious/sealious#222]
Currently field-type inheritance is achieved by manually calling methods either from the field-type-declaration or from the field-type prototype.

All the field-type methods except for `is_proper_value` should use native JS object prototype chain for easy and efficient inheritance.

**Comment by debian-sh** [comment]
https://nodejs.org/api/util.html#util_util_inherits_constructor_superconstructor

**Comment by groovy354** [comment]
It seems useful, but I think we should use native javascript prototype chain :)

**Comment by groovy354** [comment]
Moved to [ice box](https://trello.com/c/cYb7ii2u/4-use-javascript-s-prototype-chain-to-implement-field-type-inheritance)
