### ISSUE TITLE
Accept, reject interface in checker function

### ISSUE THREAD

**Issue by Delfinek** [Sealious/sealious#225]
similar to is_proper_value

**Comment by groovy354** [comment]
Contained within [this trello card](https://trello.com/c/O695rl6o/11-create-a-nice-declaration-focused-documentation-and-api-reference)

**Comment by groovy354** [comment]
Moved to [ice box](https://trello.com/c/cdgM5YO3/6-accept-reject-interface-in-access-strategy-s-checker-function)
