### ISSUE TITLE
Problem with creating new user with the same username

### ISSUE THREAD

**Issue by debian-sh** [Sealious/sealious#229]
I've noticed issue, we can create new user with the same username indefinitely (tingo & mongo).
Probably method `Sealious.Dispatcher.users.user_exists` doesn't work.
```js
15:18:31.388 - info: User pi has been created
15:18:31.404 - info:    POST /api/v1/users
            from: 127.0.0.1, mime: multipart/form-data
            result: success!
15:18:32.032 - info: User pi has been created
15:18:32.035 - info:    POST /api/v1/users
            from: 127.0.0.1, mime: multipart/form-data
            result: success!
15:18:32.533 - info: User pi has been created
15:18:32.537 - info:    POST /api/v1/users
            from: 127.0.0.1, mime: multipart/form-data
            result: success!
15:18:32.961 - info: User pi has been created
15:18:32.969 - info:    POST /api/v1/users
            from: 127.0.0.1, mime: multipart/form-data
            result: success!
```

**Comment by debian-sh** [comment]
The problem still exists on mongo & tingo.

**Comment by debian-sh** [comment]
I've discovered that after creating two users with the same name and other passwords, they are others users.

**Comment by groovy354** [comment]
Yes, currently UserManager leaves a lot to be desired. It'll be fixed when
we remove it... :)

**Comment by theadimar21** [comment]
Yeah, UserManager, nobody likes you, Sealious will be better off without
you!


W dniu piątek, 20 listopada 2015 Kuba Orlik <notifications@github.com>
napisał(a):

**Comment by groovy354** [comment]
A month later: "Come back, we love you! :<"

**Comment by debian-sh** [comment]
A month later - UserManager says: "I would like to be DispatcherManager"

**Comment by groovy354** [comment]
A year from now DispatcherManager becomes
ResourceFieldTypeStructureReferenceSubjectType

It's good we have a clear outlook for the future :)

**Comment by debian-sh** [comment]
It makes sense, especially all functions which in name have "Type". :)

**Comment by groovy354** [comment]
The future looks bright!

**Comment by modliszka** [comment]
If I can disturb such a lovely conversation... ^^
For me works when I change in `user_exists`:

			Sealious.Dispatcher.resources.find({
					username: username
				}, "user")
To:

			Sealious.Dispatcher.resources.find(
				context, {
					username: username
				}, "user")

The dispatcher's `find` function needs 3 arguments, not 2.

**Comment by debian-sh** [comment]
Yep, it's solution, probably nobody added context to this method after introduction of Context feature to Sealious.

**Comment by debian-sh** [comment]
https://github.com/Sealious/sealious/pull/247

**Comment by theadimar21** [comment]
Merged.
