### ISSUE TITLE
[dokumentacja] Okomentować kod inline'owo

### ISSUE THREAD

**Issue by groovy354** [Sealious/sealious#40]

**Comment by Delfinek** [comment]
Na razie zrezygnowaliśmy z jsdoc'a.

**Comment by Delfinek** [comment]
Dokumentation for chip-types:
[] access-strategy
[] association -interface
[] channel
[] chip-manager
[] chip
[] datastore
[] field-type
[] resource-representation
[] resource-type-field
[] resource-type

**Comment by debian-sh** [comment]
- [ ] user-manager

**Comment by groovy354** [comment]
Inline documentation is not a priority right now. We should focus more on rich declaration API documentation.
