### ISSUE TITLE
Uczynić ResourceManager, UserManager i SessionManager chipami typu serwis

### ISSUE THREAD

**Issue by groovy354** [Sealious/Sealious#55]
Aktualnie `ResourceManager`, `UserManager` i `SessionManager` są po prostu pakietami npm, które sa na twardo `require`owane w Prometeuszu. Aby ucznić kod czystszym należy przerobić te klasy na pełnoprawne serwisy prometeuszowe (czyli chipy mające swoje miejscse w ChipManager - chipy typu `service`)

**Comment by groovy354** [comment]
e8a6b26020  - przenieśliśmy User Manager. Póki co testowane tylko w trybie lokalnym

**Comment by groovy354** [comment]
Stanęło na tym, że musimy jeszcze przeczyścić to, jak dispatchery obsługują Datastore

**Comment by simplypixi** [comment]
Sealious działa w trybie lokalnym. Prace nad rozproszonym nadal trwają. W kolejnym kroku trzeba dodać w definicji dispatchera metodę "process_datastore_methods", która będzie działać na takiej samej zasadzie jak metody "process_services_methods" oraz "process_resource_manager_methods".

**Comment by groovy354** [comment]
Zdałem sobie sprawę, że trzeba będzie zmienić protokół komunikacji pomiędzy warstwą biznesową a bazy danych z REST na JSON RPC - to zdecydowanie uprości kod dispatcherów

**Comment by groovy354** [comment]
Zrobione, domergowane do mastera w b76c058d2d312978
