### ISSUE TITLE
[crashtest] Zbudowanie pola typu "color"

### ISSUE THREAD

**Issue by groovy354** [Sealious/Sealious#79]
Aby przetestować elastyczność typów pól w Prometeuszu, spróbujmy stworzyć pole typu "color". Może akceptować wartości podane zarówno w `hex`, `rgb`, `hsl`, `rgba`, `hsla` oraz nazwy kolorów html (np `red`, `green`, `gray`. 
Jednakże pola w bazie danych muszą być przechowywane w jednolitej postaci, niezależnie od formy, którą podał użytkownik - proponuję, aby był to `rgba`, gdyż wydaje mi się, że jest najbardziej zrozumiały dla maszyn.

**Comment by simplypixi** [comment]
Czyli trzeba zaimplementować pole "color" z małym konwerterem na format rgba? :P

**Comment by groovy354** [comment]
Yis. Typ pola ('field_type')

**Comment by debian-sh** [comment]
Do przetestowania do example-app

https://github.com/Sealious/sealious-base-chips/commit/6b20e3e399c2e8f5266c424db78160cecccf8624
