### ISSUE TITLE
[chat] Propozycje zmian

### ISSUE THREAD

**Issue by simplypixi** [Sealious/Sealious#82]
Jeśli wpadnie Wam do głowy jakiś pomysł, możecie go wrzucić tutaj edytując mój wpis. 
* [ ] Rozmowy wideo - postaram się tym zająć (Mariusz) jeśli nie będzie ważniejszych spraw do kodzenia (przydałby mi się ktoś do pomocy)
* [ ] Rozmowy audio
* [ ] Pełna obsługa rozmów konferencyjnych:
  * [ ] w konwersacjach możemy sprawdzić wszystkich użytkowników, którzy biorą udział w rozmowie (tip: kwestia zamiany przechowywania w kluczu user2 ID rozmówcy na tablicę ID rozmówców)
  * [ ] wybór wielu rozmówców (tip: praca na froncie, dopisanie  atrybutu "multiple" w kontrolce select)
  * [ ] przeliczanie kolorów chmurek dla rozmówców (przy l. rozmówców > 2) - opcjonalne
* [ ] Obsługa MarkDown
* [x] Zablokowanie możliwości dodawania znaczników HTML w treści wiadomości (#83)
* [ ] Dodanie możliwości rejestracji/logowania za pomocą serwisów społecznościowych
* [ ] Powiadomienia e-mail o nowych wiadomościach w konwersacji 
* [ ] Obsługa ustawień/konfiguracji chat'u. Proponuję utworzenie w bazie nowego klucza ("settings"/"options") dla dokumentu reprezentującego użytkownika. Możemy przechowywać ustawienia do różnych usług na zasadzie: settings: { chat: { ... ustwienia ... }, inna_usluga: { ... ustawienia ... } }

**Comment by debian-sh** [comment]
* [ ] Możliwość szybkiego przeskakiwania pomiędzy konwersacjami, skrót klawiaturowy
* [ ] Obsługiwanie całego interfejsu wyłącznie klawiaturą
* [ ] Obsługa emotikon

**Comment by groovy354** [comment]
Przekopiowałem listę pomysłów [tutaj](https://docs.google.com/document/d/1BINbllaXZjZsAqEeFmQ1mGaYYNOXRAmFK4DDKHeFC-8/edit?usp=sharing)
