### ISSUE TITLE
Zablokowanie dodawania znaczników HTML w treści wiadomości

### ISSUE THREAD

**Issue by simplypixi** [Sealious/Sealious#83]

**Comment by groovy354** [comment]
Dodam, że to się powinno dziać "natywnie", po stronie back-endu. Cała ta funkcjonalność, jeżeli ma być zrobiona "czysto", powinna być zawarta w jakimś nowym typie pola.
I nie zapominajmy o MarkDown :)

**Comment by simplypixi** [comment]
Spoczi ;)

**Comment by simplypixi** [comment]
Done. ;)

**Comment by groovy354** [comment]
Rozumiem, że issue został zamknięty w 5e2a1a3e280ddb9f715f1ad16da4eb7c52255a48 - ale chyba nie wszystko się spushowało :)

**Comment by simplypixi** [comment]
Jak to?

**Comment by groovy354** [comment]
Zrobione - proszę niech ktoś rozpatrzy pull requesty:
https://github.com/Sealious/sealious-base-chips/pull/15
https://github.com/Sealious/sealious-example-app/pull/4

**Comment by debian-sh** [comment]
https://github.com/Sealious/sealious-base-chips/pull/15
Jak dla mnie w porządku.

**Comment by groovy354** [comment]
Rozwiązane w https://github.com/Sealious/sealious-base-chips/commit/178aad684f4df3ecc43499005345d31362d0dffa :)
