### ISSUE TITLE
[perspektywa] Technologie frontendowe do rozpatrzenia

### ISSUE THREAD

**Issue by groovy354** [Sealious/Sealious#84]
Dodajcie własne lub komentujcie te już dopisane :)

* http://webcomponents.org/ - do komponentów wielokrotnego użytku
* https://facebook.github.io/react/ - do renderowania widoków zarówno po stronie klienta, jak i po stronie serwera

**Comment by simplypixi** [comment]
Po krókiej lekturzem myślę, że React się sprawdzi. ;) Jeszcze muszę się wgryźć w webcomponents. ;)

**Comment by groovy354** [comment]
React wydaje się brać górę, jeżeli chodzi o wsparcie deweloperów (dodatkowo WebComponents to sprawka Google'a), więc myślę, że decyzja jest jasna :)
