### ISSUE TITLE
Dofinansowanie z Unii na rozwój (jako org. non-profit)

### ISSUE THREAD

**Issue by simplypixi** [Sealious/Sealious#89]
* [x] Wstępne ogarnięcie tematu
* [ ] Jak wyglądają formalności?
* [ ] Pogadać z mamą ;)
* [ ] Porozmawiać osobiście z kimś ogarniętym z urzędu.

**Comment by theadimar21** [comment]
<opadła szczęka> serio? to byłoby hardcorowe :D

W dniu 26 lutego 2015 14:26 użytkownik Mariusz <notifications@github.com>
napisał:

**Comment by debian-sh** [comment]
Pogadać z mamą?

**Comment by simplypixi** [comment]
Tak, moja mama załatwiała już sprawy dofinansowania i - jako byla radna i obecny soltys - ma wtyki w urzędzie. :D

-----Wiadomość oryginalna-----
Od: "Arkadiusz Wieczorek" <notifications@github.com>
Wysłano: ‎2015-‎02-‎26 14:29
Do: "groovy354/Sealious" <Sealious@noreply.github.com>
DW: "Mariusz" <pixiproject@gmail.com>
Temat: Re: [Sealious] Dofinansowanie z Unii na rozwój (jako org. non-profit) (#89)

Pogadać z mamą?

**Comment by simplypixi** [comment]
Tak Adrian, serio ;P

-----Wiadomość oryginalna-----
Od: "theadimar21" <notifications@github.com>
Wysłano: ‎2015-‎02-‎26 14:28
Do: "groovy354/Sealious" <Sealious@noreply.github.com>
DW: "Mariusz" <pixiproject@gmail.com>
Temat: Re: [Sealious] Dofinansowanie z Unii na rozwój (jako org. non-profit) (#89)

<opadła szczęka> serio? to byłoby hardcorowe :D

W dniu 26 lutego 2015 14:26 użytkownik Mariusz <notifications@github.com>
napisał:

**Comment by theadimar21** [comment]
Uuu, najs, najs. Generalnie pomysł dobry, tylko pytanie na co byśmy chcieli
dofinansowanie?

**Comment by simplypixi** [comment]
Na rozwój. :)

-----Wiadomość oryginalna-----
Od: "theadimar21" <notifications@github.com>
Wysłano: ‎2015-‎02-‎26 15:20
Do: "groovy354/Sealious" <Sealious@noreply.github.com>
DW: "Mariusz" <pixiproject@gmail.com>
Temat: Re: [Sealious] Dofinansowanie z Unii na rozwój (jako org. non-profit) (#89)

Uuu, najs, najs. Generalnie pomysł dobry, tylko pytanie na co byśmy chcieli
dofinansowanie?

**Comment by groovy354** [comment]
No właśnie, czy możemy brać dofinansowanie za robociznę? Czy możemy to
tylko wydawać na konkretne sprzęty lub oprogramowanie?
Może licencje na sublime'a sobie za to kupimy :D

**Comment by theadimar21** [comment]
Proponuję część przekazać na foki.

A tak serio - na co chcielibyśmy dofinansowanie? Na służbowe laptopy,
telefony? Na wynajmowanie pomieszczenia służbowego ze stale działającym
serwerem (+ zewnętrzne IP)?

Nie powiem, że to zły pomysł, ale trzeba naprawdę przemyśleć co byłoby nam
potrzebne, ułożyć jakiś biznes-plan etc. Myślę, że w niedzielę będzie to do
przegadania.

W dniu 26 lutego 2015 15:23 użytkownik Kuba Orlik <notifications@github.com>
napisał:

> No właśnie, czy możemy brać dofinansowanie za robociznę? Czy możemy to
> tylko wydawać na konkretne sprzęty lub oprogramowanie?
> Może licencje na sublime'a sobie za to kupimy :D

**Comment by simplypixi** [comment]
Generalnie skoro można wykorzystać jakąś pulę pieniędzy to nie ma co wybrzydzać. Zgłębię temat bardziej. Ogarnę ile dofinansowania możemy się spodziewać, a w niedzielę faktycznie możemy obgadać sprawę wykorzystania tych pieniędzy. ;)

**Comment by simplypixi** [comment]
Jakby co nie mam jeszcze żadnego konkretnego info.

**Comment by debian-sh** [comment]
Prócz dofinansowania, możemy się zainteresować mikrodotacjami:
https://gratipay.com/
https://flattr.com/

**Comment by theadimar21** [comment]
I jak idą rozmowy?

**Comment by debian-sh** [comment]
https://www.funduszeeuropejskie.gov.pl/

**Comment by simplypixi** [comment]
Mama nie zdobyła żadnych konkretów.
Arek, przytoczona przez Ciebie stronka jest spoko, ale jeszcze parę tygodni
temu nic na niej nie było. ;)
Przyjrzę się jej w najbliższym czasie. Jednak z tego co już zauważyłem, nie
ma chyba rozpisanych konkursów na dofinansowanie ściśle powiązanych z
Sealiousem.

**Comment by groovy354** [comment]
Zdecydowaliśmy się na zamknięcie tematu - jeżeli będziemy robić kasę na Sealiousie, to robiąc zajebiste produkty oparte na nim :)
