### ISSUE TITLE
Początki pracy nad CI

### ISSUE THREAD

**Issue by groovy354** [Sealious/Sealious#90]

**Comment by debian-sh** [comment]
- [x] przygotowanie koncepcyjnych palety barw
- [ ] dobór odpowiedniej palety (identyfikacja koloru bazowego i jego dopełniających)
- [ ] przygotowanie propozycji - wariantów logo
- [ ] przygotowanie szablonu prezentacji
- [ ] przygotowanie mockup'u witryny

**Comment by debian-sh** [comment]
- [x] przygotowanie koncepcyjnych palety barw
- [ ] dobór odpowiedniej palety (identyfikacja koloru bazowego i jego dopełniających)
- [ ] przygotowanie propozycji - wariantów logo
- [ ] przygotowanie szablonu prezentacji
- [ ] przygotowanie mockup'u witryny

**Comment by groovy354** [comment]
prace nad CI kontynuowane aktywnie na branchu gh-pages. Issue zamykam :)
